webdriver.wait.for.timeout=5000
serenity.console.colors = true

# Appears at the top of the reports
serenity.project.name = Relatório de testes de API do ServeRest

# Root package for any JUnit acceptance tests
#requisitions.test.root=net.thucydides.showcase.junit.features

# Customise your riequirements hierarchy
#requisitions.requirement.types=feature, story

serenity.requirements.encoding = UTF-8
serenity.logging = VERBOSE
